# Generated by Django 4.0.5 on 2022-07-05 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0003_course_name_course_page_course_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='courses',
        ),
    ]
