# Generated by Django 4.0.5 on 2022-07-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0004_remove_instructor_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='courses',
            field=models.ManyToManyField(to='instructors.course'),
        ),
    ]
