# Generated by Django 4.0.5 on 2022-07-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0005_instructor_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='languages',
        ),
        migrations.AddField(
            model_name='instructor',
            name='languages',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
