# Generated by Django 4.0.5 on 2022-07-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0006_remove_instructor_languages_instructor_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='languages',
        ),
        migrations.AddField(
            model_name='instructor',
            name='languages',
            field=models.ManyToManyField(to='instructors.language'),
        ),
    ]
